//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Player/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""f8470071-89b9-4f12-96d6-d7526a2deaf0"",
            ""actions"": [
                {
                    ""name"": ""LookAt"",
                    ""type"": ""Value"",
                    ""id"": ""a632834a-6b72-4794-89ee-fcf0c014fb12"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""ec48ee62-e7d0-4169-a910-28a3eec78983"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchBullet1"",
                    ""type"": ""Button"",
                    ""id"": ""c062b873-0e19-45f8-907f-14a3e6227e8e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchBullet2"",
                    ""type"": ""Button"",
                    ""id"": ""00a1ddd6-cca8-444b-b136-7da906c3cf21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchBullet3"",
                    ""type"": ""Button"",
                    ""id"": ""e959e7de-0d1e-4b00-99a5-3f09d9f2ea79"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchBullet4"",
                    ""type"": ""Button"",
                    ""id"": ""5c72d4f4-9ebd-4824-96f9-170aa6e6e7f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""da8b7f6f-2568-4b99-9c32-26526610d264"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookAt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2085d95-1277-4219-a1d1-c80c363dffe0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5499319-2bce-4971-bd71-2b7742f372e3"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchBullet1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b76182fd-906c-4404-9086-a1fe391b7721"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchBullet2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a9e0c9c-041c-48eb-8b1f-b37061b69c32"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchBullet3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbd3cefa-929c-433a-96b7-45bee19b7eea"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchBullet4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_LookAt = m_Player.FindAction("LookAt", throwIfNotFound: true);
        m_Player_Shoot = m_Player.FindAction("Shoot", throwIfNotFound: true);
        m_Player_SwitchBullet1 = m_Player.FindAction("SwitchBullet1", throwIfNotFound: true);
        m_Player_SwitchBullet2 = m_Player.FindAction("SwitchBullet2", throwIfNotFound: true);
        m_Player_SwitchBullet3 = m_Player.FindAction("SwitchBullet3", throwIfNotFound: true);
        m_Player_SwitchBullet4 = m_Player.FindAction("SwitchBullet4", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_LookAt;
    private readonly InputAction m_Player_Shoot;
    private readonly InputAction m_Player_SwitchBullet1;
    private readonly InputAction m_Player_SwitchBullet2;
    private readonly InputAction m_Player_SwitchBullet3;
    private readonly InputAction m_Player_SwitchBullet4;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @LookAt => m_Wrapper.m_Player_LookAt;
        public InputAction @Shoot => m_Wrapper.m_Player_Shoot;
        public InputAction @SwitchBullet1 => m_Wrapper.m_Player_SwitchBullet1;
        public InputAction @SwitchBullet2 => m_Wrapper.m_Player_SwitchBullet2;
        public InputAction @SwitchBullet3 => m_Wrapper.m_Player_SwitchBullet3;
        public InputAction @SwitchBullet4 => m_Wrapper.m_Player_SwitchBullet4;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @LookAt.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLookAt;
                @LookAt.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLookAt;
                @LookAt.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLookAt;
                @Shoot.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @SwitchBullet1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchBullet1;
                @SwitchBullet1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchBullet1;
                @SwitchBullet1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchBullet1;
                @SwitchBullet2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchBullet2;
                @SwitchBullet2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchBullet2;
                @SwitchBullet2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchBullet2;
                @SwitchBullet3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchBullet3;
                @SwitchBullet3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchBullet3;
                @SwitchBullet3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchBullet3;
                @SwitchBullet4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchBullet4;
                @SwitchBullet4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchBullet4;
                @SwitchBullet4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchBullet4;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LookAt.started += instance.OnLookAt;
                @LookAt.performed += instance.OnLookAt;
                @LookAt.canceled += instance.OnLookAt;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @SwitchBullet1.started += instance.OnSwitchBullet1;
                @SwitchBullet1.performed += instance.OnSwitchBullet1;
                @SwitchBullet1.canceled += instance.OnSwitchBullet1;
                @SwitchBullet2.started += instance.OnSwitchBullet2;
                @SwitchBullet2.performed += instance.OnSwitchBullet2;
                @SwitchBullet2.canceled += instance.OnSwitchBullet2;
                @SwitchBullet3.started += instance.OnSwitchBullet3;
                @SwitchBullet3.performed += instance.OnSwitchBullet3;
                @SwitchBullet3.canceled += instance.OnSwitchBullet3;
                @SwitchBullet4.started += instance.OnSwitchBullet4;
                @SwitchBullet4.performed += instance.OnSwitchBullet4;
                @SwitchBullet4.canceled += instance.OnSwitchBullet4;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnLookAt(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnSwitchBullet1(InputAction.CallbackContext context);
        void OnSwitchBullet2(InputAction.CallbackContext context);
        void OnSwitchBullet3(InputAction.CallbackContext context);
        void OnSwitchBullet4(InputAction.CallbackContext context);
    }
}
